version: '5.0.1'

services:
  api:
    build:
      context: ./backend/ObstaRace.API/ObstaRace.API
      dockerfile: Dockerfile
    container_name: obstarace_api
    ports:
      - "5235:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/obstarace.db
    volumes:
    
      - ./backend/ObstaRace.API/ObstaRace.API/ObstaRace.db:/app/obstarace.db
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: obstarace_client
    ports:
      - "5173:80"
    depends_on:
      - api